name: Run Robot Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:  New Tese
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: poetry install

      - name: Run Robot Framework Tests
        run: poetry run robot ./
